# -*- coding: utf-8 -*-
"""Open_AI_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jCWA4WOrLa8kt8UaYiDCMKqYCk2Ce2Q0
"""

!pip install pytesseract
!pip install pdf2image
!apt-get install poppler-utils
!apt-get install tesseract-ocr

from PIL import Image
import pytesseract
from pdf2image import convert_from_path
from PIL import Image
import pytesseract

# PDF dosyasını görüntülere dönüştür
pages = convert_from_path('/content/hamza.pdf')

for i, page in enumerate(pages):
    page.save(f'page_{i}.jpg', 'JPEG')

# Dönüştürülmüş görüntüyü aç
image = Image.open('page_0.jpg')

# Metin tanıma işlemini gerçekleştirin
text = pytesseract.image_to_string(image)

# Tanınan metni yazdırın
print(text)
with open('metin_cikti.txt', 'w', encoding='utf-8') as text_file:
    text_file.write(text)

!pip install openai

import openai

# OpenAI API anahtarınızı buraya ekleyin
api_key = ""

# OpenAI API istemcisini başlatın
openai.api_key = api_key

# Metin dosyasının içeriğini okuyun
with open("/content/metin_cikti.txt", "r") as file:
    text = file.read()

# OpenAI API'sini kullanarak metindeki kişileri tanımlama
response = openai.Completion.create(
  engine="davinci",
  prompt=f"Bir metin dosyası içindeki kişileri tanımla:\n{text}\nKişiler:",
  max_tokens=50
)

# API yanıtını yazdır
print(response.choices[0].text)