# -*- coding: utf-8 -*-
"""Copy of SpaceEYES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y_Qr1DKGkMml0tFXMiWscL8u67ph5C-E
"""

!pip install openai

#!pip install openai
#import boto3
import os
import pandas as pd
import openai

openai.api_key = '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'

#load data
df = pd.read_csv('sample_ais.csv')
df

df = df[["lat", "long", "sog", "cog", "timestamp", "mmsi"]]
df = df.dropna()
df["combined"] = (
    "Latitude: " + df.lat.astype(str) + "; Longitude: " + df.long.astype(str)+"; Timestamp: " + df.timestamp.astype(str) + "; Vessel_id: " + df.mmsi.astype(str)
)

df.head()

sample = df.head(10)

sample['ada_embedding'] = sample.combined.apply(lambda x: get_embedding(x, model='text-embedding-ada-002'))

sample

def get_embedding(text, model="text-embedding-ada-002"):
    text = text.replace("\n", " ")
    return openai.Embedding.create(input = [text], model=model)['data'][0]['embedding']

# Iterate all rows using DataFrame.iterrows()
for row in df.iterrows():
    print (index,row["Fee"], row["Courses"])

# serial example, with one story completion per request
for i in iterrows(df):
    response = openai.Embedding.create(input = i.get('combined'),model="text-embedding-ada-002",max_tokens=20,
    )
    print(response)

from tenacity import (
    retry,
    stop_after_attempt,
    wait_random_exponential,
)  # for exponential backoff


@retry(wait=wait_random_exponential(min=1, max=50), stop=stop_after_attempt(6))
def completion_with_backoff(**kwargs):
    return openai.Embeddings.create(**kwargs)



embeddings = completion_with_backoff(openai.Embedding.create(input = df.combined, model=model)['data'][0]['embedding']))



