#!/usr/bin/env python3
import uuid
import openai
import sys
import gpt_utils

gpt_utils.gpt_init()
gpt_utils.set_openai_api_key()

arg = " ".join(sys.argv[1:])

messages = [
    gpt_utils.create_openai_message(
        gpt_utils.gpt_system_role,
        "You are ChatGPT, a large language model trained by OpenAI."
        " Answer as concisely as possible.",
    ),
    gpt_utils.create_openai_message(
        gpt_utils.gpt_user_role,
        f"Answer with only the actual command without any intro "
        f"or explanation. What is the linux command to {arg}",
    ),
]

r = openai.ChatCompletion.create(
    model="gpt-3.5-turbo", temperature=0, messages=messages
)

code_uuid = str(uuid.uuid4())

text = r["choices"][0]["message"]["content"]
text, lang = gpt_utils.extract_code_from_response(text)

gpt_utils.save_log("howto.log", arg, code_uuid, text)

print(text)
