#!/usr/bin/env python3
import openai
import sys
import gpt_utils

gpt_utils.gpt_init()
gpt_utils.set_openai_api_key()

messages = [
    gpt_utils.create_openai_message(
        gpt_utils.gpt_system_role,
        "You will be provided with a piece of Python code, "
        "and your task is to provide a unit test class for the code. "
        "Do not include the code itself in the test class.",
    ),
]

content = sys.stdin.read()
code_uuid, content = gpt_utils.extract_uuid_and_content(content)
messages.append(
    gpt_utils.create_openai_message(gpt_utils.gpt_user_role, content)
)

r = openai.ChatCompletion.create(
    model="gpt-3.5-turbo", temperature=0, messages=messages
)

text = r["choices"][0]["message"]["content"]
gpt_utils.save_log("tests.log", content, code_uuid, text)
text, lang = gpt_utils.extract_code_from_response(text)
gpt_utils.save_code("test", code_uuid, text, lang)

print(f"START_UUID:{code_uuid}:END_UUID")
print(text)
