#!/usr/bin/env python3
import fileinput
import openai
import os
from dotenv import load_dotenv

load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

if __name__ == '__main__':
    query = '\n'.join(fileinput.input())
    response = openai.ChatCompletion.create(
        #model='gpt-3.5-turbo',
        model='gpt-4',
        messages=[
            dict(role='user', content=query)
        ],
        temperature=0.0
    )
    print(response['choices'][0]['message']['content'])
