from openai import OpenAI

# Define the API key file path
API_KEY = 'textfile_with_api_key.txt'

# Initialize the OpenAI client
with open(API_KEY, 'r') as file:
    # Read the contents of the file to obtain the API key
    key = file.read()
client = OpenAI(api_key=key)

def chat(user_input):
    '''
    Parameters: user_input (string) - User's input for the chat
    Returns: completion - Response generated by the chat model
    Does: Creates a chat completion using the user's input and retrieves a response.
    '''
    # Create a chat completion using the user's input, with a maximum of 200 tokens
    completion = client.chat.completions.create(
        model='gpt-4',
        messages=[
            {'role': 'system', 'content': 'You are a financial advisor helping a customer to invest in the stock market, and you provide your own suggestions.'},
            {'role': 'user', 'content': user_input}
        ],
        max_tokens=2000  # Setting the maximum number of tokens
    )
    return completion

def main():
    print('Ask a question regarding a sector in the stock market or information about a specific stock.')
    print('')
    user_input = input('Enter a message: ')
    completion = chat(user_input)
    print('')
    # Print the response, removing newline characters
    print(completion.choices[0].message.content.replace('\n', ' '))

if __name__ == '__main__':
    main()
