# -*- coding: utf-8 -*-
"""openaiapi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jim0OkLREPmGWowPE3GPjqMacCLAd20M
"""

!pip install os
!pip install openai

import os
import openai
import random
import pandas as pd

file_path = '/content/names.txt'

with open(file_path, 'r') as file:
    content = file.read()
names=content.split('\n')
# print(type(names))

excel_file_path = '/content/export-all-urls.CSV'
df = pd.read_csv(excel_file_path)
df['Title'] = df['Title'].str.replace(r'[^\w\s]', '')

df.insert(1, 'Name-Title', None)
df.insert(2, 'Description', None)

openai.api_key = "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"
for i,j in df['Title'].items():
  title = openai.Completion.create(
    model="text-davinci-003",
    prompt=f"unique product title in 3 words for the following description: \n\nProduct description: {j}",
    temperature=0.8,
    max_tokens=9,
    top_p=1.0,
    frequency_penalty=0.9,
    presence_penalty=0.0
  )
  desc = openai.Completion.create(
    model="text-davinci-003",
    prompt=f"5 selling points in bullet format for the following description: \n\nProduct description: {j}",
    temperature=0.5,
    max_tokens=100,
    top_p=1.0,
    frequency_penalty=0.0,
    presence_penalty=0.0
  )

  df['Name-Title'][i] = random.choice(names) +' - '+ title.choices[0].text.replace('\n\n', '')
  df['Description'][i] = desc.choices[0].text + "\nFree Worldwide Shipping & 100% Money-Back Guarantee."
  print(df['Name-Title'][i])
  print(df['Description'][i])

df

df.to_excel('/content/export.xlsx', index=False)

print("Dataframe saved to Excel file successfully.")

