import discord
import openai
import queue
openai.organization = ""
openai.api_key
from discord.ext import commands

bot = commands.Bot(command_prefix='!')


@bot.event
async def on_ready():
    print(f'{bot.user.name} has connected to Discord!')

def CreateResponse(message,sender):
    messages = {}
    q = queue.Queue()
    q.put(message)
    QueueLength = len(q)
    while(q.empty() == False):
        dm = q.get()
        if sender not in messages:
            messages[sender] = []
        messages[sender].append(dm)
        response = openai.Completion.create(
            model="text-davinci-002",
            prompt=f"Generate a response to this:{dm} and also when generating the response take in the conversional history {messages[sender]} and also when genreating a repsonse keep in mind their name {sender}",
            temperature=1,
            max_tokens=1024,
            top_p=1,
            frequency_penalty=0.5,
            presence_penalty=0
        )
        return response["choices"][0]["text"]

@bot.command(name='Actor')
async def actor(ctx, *, message):
    l = ctx.message.content()
    a = ctx.message.author()
    response = CreateResponse(message.content,message.author)
    discord.Client.send_message(response)
    discord.Client.send_message("The above response was generated by a robot!")
    await ctx.send(response)


