from pydantic import BaseModel, Field
from openai.types.chat.completion_create_params import ResponseFormat
from typing import Literal


__all__ = ['settings', 'chat_settings']


class Settings(BaseModel, validate_assignment=True):
    action_prefix: str = Field(default=':', max_length=1)


settings = Settings()


class ChatSettings(BaseModel, validate_assignment=True):
    '''
    model: ID of the model to use. See the
        [model endpoint compatibility](https://platform.openai.com/docs/models/model-endpoint-compatibility)
        table for details on which models work with the Chat API.

    frequency_penalty: Number between -2.0 and 2.0. Positive values penalize new tokens based on their
        existing frequency in the text so far, decreasing the model's likelihood to
        repeat the same line verbatim.

        [See more information about frequency and presence penalties.](https://platform.openai.com/docs/guides/gpt/parameter-details)

    function_call: Deprecated in favor of `tool_choice`.

        Controls which (if any) function is called by the model. `none` means the model
        will not call a function and instead generates a message. `auto` means the model
        can pick between generating a message or calling a function. Specifying a
        particular function via `{"name": "my_function"}` forces the model to call that
        function.

        `none` is the default when no functions are present. `auto`` is the default if
        functions are present.

    functions: Deprecated in favor of `tools`.

        A list of functions the model may generate JSON inputs for.

    logit_bias: Modify the likelihood of specified tokens appearing in the completion.

        Accepts a JSON object that maps tokens (specified by their token ID in the
        tokenizer) to an associated bias value from -100 to 100. Mathematically, the
        bias is added to the logits generated by the model prior to sampling. The exact
        effect will vary per model, but values between -1 and 1 should decrease or
        increase likelihood of selection; values like -100 or 100 should result in a ban
        or exclusive selection of the relevant token.

    max_tokens: The maximum number of [tokens](/tokenizer) to generate in the chat completion.

        The total length of input tokens and generated tokens is limited by the model's
        context length.
        [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken)
        for counting tokens.

    n: How many chat completion choices to generate for each input message.

    presence_penalty: Number between -2.0 and 2.0. Positive values penalize new tokens based on
        whether they appear in the text so far, increasing the model's likelihood to
        talk about new topics.

        [See more information about frequency and presence penalties.](https://platform.openai.com/docs/guides/gpt/parameter-details)

    response_format: An object specifying the format that the model must output.

        Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the
        message the model generates is valid JSON.

        **Important:** when using JSON mode, you **must** also instruct the model to
        produce JSON yourself via a system or user message. Without this, the model may
        generate an unending stream of whitespace until the generation reaches the token
        limit, resulting in increased latency and appearance of a "stuck" request. Also
        note that the message content may be partially cut off if
        `finish_reason="length"`, which indicates the generation exceeded `max_tokens`
        or the conversation exceeded the max context length.

    seed: This feature is in Beta. If specified, our system will make a best effort to
        sample deterministically, such that repeated requests with the same `seed` and
        parameters should return the same result. Determinism is not guaranteed, and you
        should refer to the `system_fingerprint` response parameter to monitor changes
        in the backend.

    stop: Up to 4 sequences where the API will stop generating further tokens.

    stream: If set, partial message deltas will be sent, like in ChatGPT. Tokens will be
        sent as data-only
        [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
        as they become available, with the stream terminated by a `data: [DONE]`
        message.
        [Example Python code](https://cookbook.openai.com/examples/how_to_stream_completions).

    temperature: What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
        make the output more random, while lower values like 0.2 will make it more
        focused and deterministic.

        We generally recommend altering this or `top_p` but not both.

    tool_choice: Controls which (if any) function is called by the model. `none` means the model
        will not call a function and instead generates a message. `auto` means the model
        can pick between generating a message or calling a function. Specifying a
        particular function via
        `{"type: "function", "function": {"name": "my_function"}}` forces the model to
        call that function.

        `none` is the default when no functions are present. `auto` is the default if
        functions are present.

    tools: A list of tools the model may call. Currently, only functions are supported as a
        tool. Use this to provide a list of functions the model may generate JSON inputs
        for.

    top_p: An alternative to sampling with temperature, called nucleus sampling, where the
        model considers the results of the tokens with top_p probability mass. So 0.1
        means only the tokens comprising the top 10% probability mass are considered.

        We generally recommend altering this or `temperature` but not both.

    user: A unique identifier representing your end-user, which can help OpenAI to monitor
        and detect abuse.
        [Learn more](https://platform.openai.com/docs/guides/safety-best-practices/end-user-ids).

    extra_headers: Send extra headers

    extra_query: Add additional query parameters to the request

    extra_body: Add additional JSON properties to the request

    timeout: Override the client-level default timeout for this request, in seconds
'''
    model: Literal[
        'gpt-4-1106-preview',
        'gpt-4-vision-preview',
        'gpt-4',
        'gpt-4-0314',
        'gpt-4-0613',
        'gpt-4-32k',
        'gpt-4-32k-0314',
        'gpt-4-32k-0613',
        'gpt-3.5-turbo-1106',
        'gpt-3.5-turbo',
        'gpt-3.5-turbo-16k',
        'gpt-3.5-turbo-0301',
        'gpt-3.5-turbo-0613',
        'gpt-3.5-turbo-16k-0613',
    ] = 'gpt-3.5-turbo'
    temperature: float = Field(default=1.0, ge=0.0, le=2.0)
    max_tokens: int | None = None
    top_p: float = Field(default=1.0, ge=0.0, le=1.0)
    frequency_penalty: float = Field(default=0.0, ge=-2.0, le=2.0)
    presence_penalty: float = Field(default=0.0, ge=-2.0, le=2.0)
    response_format: ResponseFormat = {'type': 'text'}  # 'json_object'


chat_settings = ChatSettings()
