import streamlit as st 
from dotenv import load_dotenv
import os 
import openai
from diffusers import StableDiffusionPipeline
import torch
from apikey import apikey

load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")
#os.environ["OPENAI_API_KEY"] = apikey

#function to generate AI based images using OpenAI Dall-E
def img_genration():
    def generate_images_using_openai(text):
        response = openai.Image.create(prompt= text, n=1, size="512x512")
        image_url = response['data'][0]['url']
        return image_url


    st.title("Image generation using Open AI")
    st.write("image generatiopn.")   
    input_prompt = st.text_input("Enter your text prompt")
    if input_prompt is not None:
        if st.button("Generate Image"):
          image_url = generate_images_using_openai(input_prompt)
          st.image(image_url, caption="Generated by DALL-E")

 

if __name__ == "__main__":
    img_genration()  