"""
This type stub file was generated by pyright.
"""

import jsonformer
from typing import TYPE_CHECKING
from langchain.llms.huggingface_pipeline import HuggingFacePipeline
from langchain_experimental.pydantic_v1 import root_validator

"""Experimental implementation of jsonformer wrapped LLM."""
if TYPE_CHECKING:
    ...
def import_jsonformer() -> jsonformer:
    """Lazily import jsonformer."""
    ...

class JsonFormer(HuggingFacePipeline):
    """Jsonformer wrapped LLM using HuggingFace Pipeline API.

    This pipeline is experimental and not yet stable.
    """
    json_schema: dict = ...
    max_new_tokens: int = ...
    debug: bool = ...
    @root_validator
    def check_jsonformer_installation(cls, values: dict) -> dict:
        ...
    


