"""
This type stub file was generated by pyright.
"""

from typing import Any
from langchain.chat_models.base import BaseChatModel

logger = ...
class ChatLlamaAPI(BaseChatModel):
    client: Any
    ...


