"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional
from langchain import LLMChain
from langchain.base_language import BaseLanguageModel
from langchain.callbacks.manager import Callbacks

class ResponseGenerationChain(LLMChain):
    """Chain to execute tasks."""
    @classmethod
    def from_llm(cls, llm: BaseLanguageModel, verbose: bool = ...) -> LLMChain:
        ...
    


class ResponseGenerator:
    def __init__(self, llm_chain: LLMChain, stop: Optional[List] = ...) -> None:
        ...
    
    def generate(self, inputs: dict, callbacks: Callbacks = ..., **kwargs: Any) -> str:
        """Given input, decided what to do."""
        ...
    


def load_response_generator(llm: BaseLanguageModel) -> ResponseGenerator:
    ...

