from api_keys import get_openai_key
from openai import OpenAI

client = OpenAI(api_key=get_openai_key())

def get_story_and_image_prompts():    
    system_instruction = ( 
    "You are hosting a text adventure game. Start an exciting story. "
    "Keep it very brief, to keep the player engaged. "
    "Then, ask the player to make a choice, but don't tell them too much about the choice. "
    "Instead, clearly separate, provide two descriptions for images to be generated by DALL-E 3. "
    "These are the choices the player will have to make. "
    "Mark the beginning of the image descriptions with 'IMAGE PROMPT 1:' and 'IMAGE PROMPT 2:'. "
    "Make the image prompts detailed. "
    )
    user_input = "Begin the story"
    response = client.chat.completions.create(
        model="gpt-3.5-turbo-1106",
        #model="gpt-4-1106-preview",
        messages=[
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": user_input}
        ]
    )

    content = response.choices[0].message.content

    # Find the index where "IMAGE PROMPT 1:" starts in the content
    # Extract the story part from the beginning of the content up to the start of "IMAGE PROMPT 1:"
    story_end_idx = content.find("IMAGE PROMPT 1:")
    story = content[:story_end_idx].strip()
    
    # Calculate the starting index of the first image prompt by adding the length of "IMAGE PROMPT 1:" to its starting index
    # Find the index where "IMAGE PROMPT 2:" starts in the content
    # Extract the first image prompt from the content using the calculated start and end indices
    image_prompt_1_start_idx = story_end_idx + len("IMAGE PROMPT 1:")
    image_prompt_1_end_idx = content.find("IMAGE PROMPT 2:")
    image_prompt_1 = content[image_prompt_1_start_idx:image_prompt_1_end_idx].strip()

    image_prompt_2_start_idx = image_prompt_1_end_idx + len("IMAGE PROMPT 2:")
    image_prompt_2 = content[image_prompt_2_start_idx:].strip()

    return story, image_prompt_1, image_prompt_2

def continue_story(previous_story, user_choice):
    system_instruction = ( 
    "You are hosting a text adventure game. "
    "The user makes their choice by clicking on an image, whcih is the prompt you will see. "
    "Continue the narrative based on the user's last choice. "
    "Keep it very brief to keep the player engaged. "
    "Then, ask the player to make a choice, but don't tell them too much about the choice. "
    "Instead, clearly separate, provide two descriptions for images to be generated by DALL-E 3. "
    "These are the choices the player will have to make. "
    "Mark the beginning of the image descriptions with 'IMAGE PROMPT 1:' and 'IMAGE PROMPT 2:'. "
    "Make the image prompts detailed. "
    "The image prompts are only for Dall-e and not for the player to see. "
    )
 
    # Append the user's choice to the previous story
    updated_story = f"{previous_story}\nImage (prompt) picked by user:\n{user_choice}\n"
    print("Updated story: ")
    print(updated_story)

    response = client.chat.completions.create(
        model="gpt-3.5-turbo-1106",
        #model="gpt-4-1106-preview",
        messages=[
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": updated_story}
        ]
    )

    content = response.choices[0].message.content

    # Parse the content to extract the next part of the story and new image prompts
    # This parsing logic is similar to the one in get_story_and_image_prompts
    next_story_end_idx = content.find("IMAGE PROMPT 1:")
    next_story = content[:next_story_end_idx].strip()

    next_image_prompt_1_start_idx = next_story_end_idx + len("IMAGE PROMPT 1:")
    next_image_prompt_1_end_idx = content.find("IMAGE PROMPT 2:")
    next_image_prompt_1 = content[next_image_prompt_1_start_idx:next_image_prompt_1_end_idx].strip()

    next_image_prompt_2_start_idx = next_image_prompt_1_end_idx + len("IMAGE PROMPT 2:")
    next_image_prompt_2 = content[next_image_prompt_2_start_idx:].strip()

    return next_story, next_image_prompt_1, next_image_prompt_2


def generate_image(prompt):
  response = client.images.generate(
    model="dall-e-2",
    #model="dall-e-3",
    prompt=prompt,
    size="1024x1024",
    quality="standard",
    n=1,
  )
  print("Image generated")
  return response